apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubemonkey.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
    config.toml: |
      [kubemonkey]
      dry_run = {{ .Values.config.dryRun }}
      run_hour = {{ .Values.config.runHour }}
      start_hour = {{ .Values.config.startHour }}
      end_hour = {{ .Values.config.endHour }}
      blacklisted_namespaces = ["{{ .Values.config.blacklistedNamespaces }}"]
      whitelisted_namespaces = ["{{ .Values.config.whitelistedNamespaces }}"]
      time_zone = "{{ .Values.config.timeZone }}"