{{- if and .Values.serviceMonitor.enabled .Values.config.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kubemonkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubemonkey.name" . }}
    chart: {{ template "kubemonkey.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.serviceMonitor.additionalLabels }}
{{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "kubemonkey.name" . }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
