---

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-monkey-config-map
      namespace: kube-system
    data:
      config.toml: |
        [kubemonkey]
        run_hour = 20
        start_hour = 21
        end_hour = 23
        blacklisted_namespaces = ["kube-system"]
        whitelisted_namespaces = [ "default", "test-kill-namespace" ]
        time_zone = "Australia/Melbourne"
        graceperiod_sec= 10
        [notifications]
          enabled = true
          reportSchedule = true
          [notifications.attacks]
            endpoint = "test1"
            message = '''{"foo":"bar","bar":"foo"}'''
            headers = ["header1Key:header1Value", "header2Key:header2Value" ]
