---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: busybox-disabled
    namespace: default
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: busybox-disabled
          kube-monkey/disabled: "true"
      spec:
        containers:
          - name: busybox
            image: busybox
            command:
              - sleep
              - "3600"
            imagePullPolicy: IfNotPresent
