---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      dry_run = false
      blacklisted_namespaces = ["kube-system"]
      safe_mode = false
      ident_label_key = "app"
      [debug]
      enabled = true
      schedule_delay = 60
      force_should_kill = true
      schedule_immediate_kill = true
