# Default values for kubemonkey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# The service account the pods will use to interact with the Kubernetes API
serviceAccount:
  # If set, an existing Service Account is used. Else a Service Account is created automatically
  name: ""

rbac:
  enabled: true

image:
  repository: ayushsobti/kube-monkey
  tag: v0.4.1
  pullPolicy: IfNotPresent
imagePullSecrets: {}
config:
  dryRun: true  
  runHour: 8
  startHour: 10
  endHour: 16
  blacklistedNamespaces:
    - kube-system
  whitelistedNamespaces:  []
  timeZone: America/New_York
  debug:
   enabled: false # if you want to enable debugging and see how pods killed immediately set enabled and schedule_immediate_kill to true
   schedule_immediate_kill: false
  notifications:
   enabled: false
   proxy: ""
   attacks: ""

args:
  logLevel: 5
  logDir: /var/log/kube-monkey

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
