name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.15
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: make test
      
      - name: Build and push Docker images on new git tags
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ayushsobti/kube-monkey
          tag_with_ref: true
          tags: latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
